# Generated by Django 5.2 on 2025-12-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_profile',
            name='position',
            field=models.CharField(choices=[('SYSTEM_ADMIN', 'System Admin'), ('STAFF', 'Staff')], default='SYSTEM_ADMIN', max_length=100),
        ),
    ]
