# Generated by Django 5.2 on 2025-12-06 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_alter_admin_profile_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='session_feedback',
            name='session',
        ),
        migrations.DeleteModel(
            name='Awareness_Sessions',
        ),
    ]
