# Generated by Django 5.2 on 2025-12-06 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_session_feedback_session_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session_Feedback',
        ),
    ]
