# Generated by Django 5.2 on 2025-12-06 08:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_delete_session_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Awareness_Sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('session_mode', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], max_length=10)),
                ('package', models.CharField(choices=[('BASIC_ONLINE', 'Basic Online'), ('STANDARD_ONLINE', 'Standard Online'), ('PREMIUM_ONLINE', 'Premium Online'), ('BASIC_OFFLINE', 'Basic Offline'), ('STANDARD_OFFLINE', 'Standard Offline'), ('PREMIUM_OFFLINE', 'Premium Offline')], max_length=50)),
                ('preferred_date', models.DateField()),
                ('location', models.TextField(blank=True, null=True)),
                ('participants', models.PositiveIntegerField(default=50)),
                ('package_price', models.PositiveIntegerField(default=0)),
                ('extra_price', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('payment_status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PROCESSING', 'Processing'), ('PAID', 'Paid'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], default='UNPAID', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.business_profile')),
                ('payment_record', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.payments')),
            ],
        ),
        migrations.CreateModel(
            name='Session_Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(default=5)),
                ('feedback_text', models.TextField(blank=True)),
                ('submitted_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('business', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.awareness_sessions')),
            ],
        ),
    ]
