# Generated by Django 5.2 on 2025-12-07 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_awareness_sessions_payment_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='featured_image',
            field=models.ImageField(blank=True, default='blog_images/default_blog.png', null=True, upload_to='blog_images/'),
        ),
    ]
