# Generated by Django 5.2 on 2025-12-08 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_blogs_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaints',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='date_of_occurrence',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='complaints',
            name='service_type',
            field=models.CharField(blank=True, choices=[('REPORT', 'Report Only'), ('GUIDE', 'Report + Guide'), ('COMPLETE', 'Complete Solution')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='status',
            field=models.CharField(blank=True, default='Pending', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='complaints',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ComplaintFiles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='complaint_files/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='app1.complaints')),
            ],
        ),
    ]
