# Generated by Django 5.2 on 2026-01-12 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_complaints_additional_notes_complaints_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_file', models.FileField(upload_to='completion_reports/')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='completion', to='app1.complaints')),
                ('hacker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.hacker_profile')),
            ],
        ),
    ]
