# Generated by Django 5.2 on 2026-01-30 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_complaints_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='awareness_sessions',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.payments'),
        ),
    ]
