# Generated by Django 5.2 on 2026-02-09 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_hackerpayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='paid_for',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
