# Generated by Django 5.2 on 2026-02-09 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_payments_paid_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='paid_for',
            field=models.CharField(default='NULL', max_length=50),
        ),
    ]
