# Generated by Django 5.2 on 2026-02-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0016_alter_payments_paid_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='status',
            field=models.CharField(default='Pending', max_length=50, null=True),
        ),
    ]
