# Generated by Django 5.2 on 2026-02-09 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0017_alter_payments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='paid_for',
            field=models.CharField(blank=True, choices=[('COMPLAINT', 'Complaint'), ('SESSION', 'Awareness Session'), ('HACKER_PAYOUT', 'Hacker Payout')], max_length=30, null=True),
        ),
    ]
